language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install bs4
  - pip install flake8 autopep8

script:
  - flake8 --ignore=E501
  - autopep8 -r . --diff | tee check_autopep8
  - test ! -s check_autopep8
  - python AtCoderClient.py arc050 --without-login

notifications:
  email: false
